### PR TITLE
0.8.0 snapshot

### PR DESCRIPTION
**Pull request by dzgrx**
the exception may cause the schedule call skipped. just simply move schedule call outside.

### CODE REVIEW

**Comment by wwadge** [comment]
Thank you, but please remember that bonecp is DEPRECATED. You should migrate to HikariCP instead.

**Comment by quaff** [comment]
@wwadge , why deprecate bonecp? It's a successful project.

**Comment by wwadge** [comment]
For the following reasons:
- It's mostly unmaintained now
- The code is rather old now and there are better solutions out there. Most notably HikariCP is faster, more stable and more supported.
- Binaries and this repo will still be around of course, but because it implements a datasource, migrating to an alternate pool should be very easy.

**Comment by quaff** [comment]
Thanks for your efforts , I have use bonecp for years and didn't encounter any problem.

**Pull request merged**
